[workspace]
members = ["crates/asl", "crates/spica"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = ["mirror"]

[workspace.dependencies]
jsonata-core = "2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_with = "3.21.0"
spica-asl = { path = "crates/asl" }
