[package]
name = "spica-scheduler"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
spica-engine = { workspace = true }
spica-machinery = { workspace = true }
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "time", "sync"] }
ulid.workspace = true
